// src/app/layout.tsx
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} antialiased`}
      >
        <Header />

        <main className="pt-24 pb-48 bg-white min-h-screen">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
